### ISSUE TITLE
No config files found country US

### ISSUE THREAD

**Issue by NealBozeman** [rundqvist/docker-openvpn-tinyproxy#8]
Am I expected to pre-populate config files for my provider before running the container? The README doesn't mention such thing, but I receive this on startup:

```
[2021-01-04 21:44:57 INF] [openvpn   ] Creating wevpn US vpn.
[2021-01-04 21:44:57 ERR] [openvpn   ] No config files found country US. Ignoring. 
```

Thanks in advance

**Comment by NealBozeman** [comment]
Indeed, adding an .ovpn file to the cache directory for that provider worked. Is this the expected way to do it? Or does the container usually retrieve a server from the selected VPN service?

**Comment by NealBozeman** [comment]
I suppose this isn't the scope of the repo. Seeding my cache with a few ovpn config files works great, and provides random server connections automatically through the generic server URLs provided by wevpn. I appreciate you have a generic solution for basically any VPN service. Thanks a lot!

**Comment by rundqvist** [comment]
Sorry for late reply. Hasn't been particularly active with the development recently.
Yes, for WeVPN this is the correct procedure. Since there are keys and certificates in the generated files (and I haven't yet had the time to figure out what is private and what isn't) one has to put the oven-files in the cache-folder manually.
